# This config file for Travis CI
sudo: required

services:
  - docker

git:
  quiet: true
  submodules: false

notifications:
  email:
    recipients:
      - levi.armstrong@swri.org

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
    - UPSTREAM_WORKSPACE=file
    - ROSINSTALL_FILENAME=dependencies.rosinstall
    - ROS_REPO=ros
    - NOT_TEST_INSTALL=true
    - CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Debug -DTESSERACT_ENABLE_TESTING=ON -DTESSERACT_ENABLE_RUN_TESTING=OFF"
    - ROSDEP_SKIP_KEYS="bullet3 fcl"
    - AFTER_SCRIPT='catkin test -w $CATKIN_WORKSPACE --no-deps tesseract_common tesseract_collision tesseract_environment tesseract_geometry tesseract_kinematics tesseract_motion_planners tesseract_process_planners tesseract_scene_graph tesseract_urdf'
    - PKGS_DOWNSTREAM='tesseract_ros_examples tesseract_rosutils'

jobs:
  include:
    - os: linux
      dist: xenial
      language: cpp
      env:
      - ROS_DISTRO="melodic"
      - CLANG_FORMAT_CHECK=file
      - CLANG_FORMAT_VERSION=8
      - DOCKER_IMAGE=lharmstrong/tesseract:melodic
      - AFTER_SCRIPT=""
      - BADGE=clang-format
      cache:
        directories:
          - $HOME/.ccache
    - os: linux
      dist: trusty
      language: cpp
      env:
      - ROS_DISTRO="kinetic"
      - DOCKER_IMAGE=lharmstrong/tesseract:kinetic
      - BADGE=trusty
      cache:
        directories:
          - $HOME/.ccache
    - os: linux
      dist: xenial
      language: cpp
      env:
      - ROS_DISTRO="melodic"
      - DOCKER_IMAGE=lharmstrong/tesseract:melodic
      - ROS_PARALLEL_JOBS=-j4
      - ROS_PARALLEL_TEST_JOBS=-j4
      - BADGE=xenial
      cache:
        directories:
          - $HOME/.ccache
    - os: linux
      dist: trusty
      language: cpp
      env:
      - ROS_DISTRO="kinetic"
      - ROS_REPO=ros-shadow-fixed
      - DOCKER_IMAGE=lharmstrong/tesseract:kinetic
      - BADGE=trusty-shadow
      cache:
        directories:
          - $HOME/.ccache
    - os: linux
      dist: xenial
      language: cpp
      env:
      - ROS_DISTRO="melodic"
      - ROS_REPO=ros-shadow-fixed
      - DOCKER_IMAGE=lharmstrong/tesseract:melodic
      - ROS_PARALLEL_JOBS=-j4
      - ROS_PARALLEL_TEST_JOBS=-j4
      - BADGE=xenial-shadow
      cache:
        directories:
          - $HOME/.ccache
    - os: windows
      language: cpp
      git:
        quiet: true
        submodules: true
      env: BADGE=windows
  allow_failures:
    - env: ROS_DISTRO=kinetic ROS_REPO=ros-shadow-fixed DOCKER_IMAGE=lharmstrong/tesseract:kinetic BADGE=trusty-shadow
    - env: ROS_DISTRO=melodic ROS_REPO=ros-shadow-fixed DOCKER_IMAGE=lharmstrong/tesseract:melodic ROS_PARALLEL_JOBS=-j4 ROS_PARALLEL_TEST_JOBS=-j4 BADGE=xenial-shadow

install:
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then git clone --quiet --depth=1 https://github.com/ros-industrial/industrial_ci.git .ci_config; fi
  - |
    if [ "$TRAVIS_OS_NAME" = "windows" ]; then
        unset CXX CXX_FOR_BUILD CC CC_FOR_BUILD
        choco feature disable -n=showDownloadProgress
        cd ..
        mkdir -p catkin_ws/src
        mv tesseract catkin_ws/src/
        cd catkin_ws
        choco uninstall mingw
        wget https://raw.githubusercontent.com/johnwason/source_bat/master/source_bat.bash
        source source_bat.bash 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat'
        choco source add -n=ros-win -s="https://roswin.azurewebsites.net/api/v2" --priority=1
        choco install ros-melodic-ros_base -y --execution-timeout=0
        choco install clapack
        choco install openblas
        choco install console_bridge
        source source_bat.bash 'c:\opt\ros\melodic\x64\setup.bat'
        python -m pip install --upgrade pip
        rosdep install --from-paths src --ignore-src -r -y
        /c/opt/vcpkg/vcpkg.exe install jsoncpp:x64-windows
        wstool init src
        wstool merge -t src ./src/tesseract/dependencies.rosinstall
        wstool update -t src
    fi
script:
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then .ci_config/travis.sh; fi
  - |
    if [ "$TRAVIS_OS_NAME" = "windows" ]; then
        catkin_make_isolated --install --only-pkg-with-deps tesseract tesseract_collision tesseract_common tesseract_environment tesseract_geometry tesseract_kinematics tesseract_motion_planners tesseract_process_planners tesseract_scene_graph tesseract_support tesseract_urdf tesseract_visualization --cmake-args -DCMAKE_BUILD_TYPE=Debug -DTESSERACT_ENABLE_TESTING=OFF -DTESSERACT_ENABLE_RUN_TESTING=OFF
    fi
