# 000000000000000000000000000000000000000
sudo: required
dist: trusty
services:
  - docker
cache: ccache
language: cpp
compiler: gcc
notifications:
  email:
    recipients:
      - levi.armstrong@swri.org

env:
  global:
    - TEST_BLACKLIST=bullet3_ros,fcl_ros,libccd_ros,tesseract_ext

# Build all valid Ubuntu/ROS combinations available
matrix:
  include:
  - name: "Clang Format"
    env: ROS_DISTRO=kinetic DOCKER_IMAGE=ros:kinetic-perception TEST=clang-format
  - name: "Xenial kinetic"
    env: ROS_DISTRO=kinetic DOCKER_IMAGE=ros:kinetic-perception UPSTREAM_WORKSPACE=dependencies.rosinstall CATKIN_OPTIONS=catkin.options
  - name: "Bionic Melodic"
    env: ROS_DISTRO=melodic DOCKER_IMAGE=ros:melodic-perception UPSTREAM_WORKSPACE=dependencies.rosinstall CATKIN_OPTIONS=catkin.options

script:
  - bash .travis.sh
